FROM node:20-alpine as build

WORKDIR /app

COPY web-app/package*.json ./

RUN npm install

COPY web-app/ .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]